### ISSUE TITLE
[user schema 추가]

### ISSUE THREAD

**Issue by KimSejune** [Nexters/CREW_Server#14]
user shema 추가.

position: Student/Preparation/Worker
job : Developer/Designer

**Comment by KimSejune** [comment]
enum JobType {
  Developer = "Developer",
  Designer = "Designer"
}

enum PositionType {
  Student = "Student",
  Prepare = "Prepare",
  Worker = "Worker"
}
으로 user의 col을 추가하였다.

**Comment by nayunhwan** [comment]
일단 지금 조심스럽게 말씀드리는건데, 혹시 job이랑 position을 반대로 바꿀 수 있나요?

현재 프론트는 Position이 Dev/Design 구분인데, 백에서 바꾸는게 코스트가 적을지 프론트에서 바꾸는게 코스트가 적을지 판단 부탁드립니다!

**Comment by KimSejune** [comment]
빠른 판단 감사합니다.
서버사이드에서 job/position 변경하도록 하겠습니다.

**Comment by KimSejune** [comment]
enum JobType {
  Student = "Student",
  Prepare = "Prepare",
  Worker = "Worker"
}

enum PositionType {
  Developer = "Developer",
  Designer = "Designer"
}
으로 user의 col을 변경하여서 추가하였다.
