### ISSUE TITLE
[get] evaluation

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CREW_Server#26]
[get] /evaluation/read?user_id=유저식별번호
req.query.user_id = user_id

[요구사항]
식별번호에 해당하는 user 의 evaluation 을 요청하는 것이다

[특이사항]
 요청자가 admin 일때만, 해당하는 정보를 넘겨준다.

**Comment by KimSejune** [comment]
@4whomtbts 
현준님 get일때 url에서 read가 빠져있고,
[특이사항]
요청자가 admin 일때만, 해당하는 정보를 넘겨준다. 
이 반영되어있지않습니다.
