### ISSUE TITLE
[post] Evaluation

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CREW_Server#27]
[post] evaluations/
req.body.id = user_id
req.user.id = user_admin_id
req.body.score= score
req.body.comment = comment

[요구사항]
req.body.id 로 받은 유저의 evaluation 을 작성한다.

[특이사항]
요청자가 admin 일때만, 해당요청이 유효하다.

**Comment by KimSejune** [comment]
@4whomtbts 

[특이사항]
요청자가 admin 일때만, 해당요청이 유효하다.
admin check가 안되어있습니다.

**Comment by 4whomtbts** [comment]
@KimSejune 
말씀하신 사항 https://github.com/Nexters/CREW_Server/pull/55 반영했습니다
닫겠습니다.
