### ISSUE TITLE
에러처리 

### ISSUE THREAD

**Issue by 4whomtbts** [Nexters/CREW_Server#32]
에러처리를 위한 일률적인 방법이 필요하다고 생각듭니다.

가령, 데이터베이스에서 쿼리를 조회/생성 하는 경우에, 성공여부를 받게 되는데 
실패한 케이스에는 단순히 null 을 반환하고 있는데요

<pre><code>
   class AppError { 
   ... 생략.. 
    constructor(where : string , message : string, status : number)
   ..
   메소드들
   ..
}
을 추가해서 

    if (!newEvaluation) {
      return null;
    }
  일때에, 
      if (!newEvaluation) {
      return AppError("evaluation","fail to create new evaluation",504); 
    }
  로 한 후, 
  // 자세한 구현과 처리 방법은 구상을 해보아야겠습니다만.
  const 에러 =  메소드 
  if(에러){
    res.status(404).send("at "+AppError.getWhere()+" : "+AppError.getMessage());
  }
</pre></code>

**Comment by KimSejune** [comment]
좋습니다~~~~~~!!
